### ISSUE TITLE
Can not find vk_dispatch_table_helper.h

### ISSUE THREAD

**Issue by computersarecool** [LunarG/VulkanSamples#120] opened 2017-03-28 22:09 UTC
Hi,
I am trying to build these samples according to the directions in the wiki.
I am using the SDK V. `1.0.39.1` and it looks like the file `vk_dispatch_table_helper.h` is not included or something.

I can not build the samples because I get the error:
`Error	C1083	Cannot open include file: 'vk_dispatch_table_helper.h': No such file or directory	VKLayer_overlay	C:\VulkanSDK\1.0.39.1\Samples\Layer-Samples\Overlay\overlay.cpp	30`

And when I try to run `build_windows_samples.sh` from the CMD I get:

`C:\VulkanSDK\1.0.39.1\Source\layers\vk_layer_table.cpp(22): fatal error C1083: Cannot open include file: 'vk_dispatch_t
able_helper.h': No such file or directory [C:\VulkanSDK\1.0.39.1\Samples\build\Layer-Samples\Overlay\VKLayer_overlay.vc
xproj]`

Is there some way for me to fix this?

**Comment by Tony-LunarG** [comment] 2017-03-29 18:56
Verified missing in sdk 1.0.39.1 and present in 1.0.39.0, and I seem to remember it was missing in an early pre-release version of 1.0.39.0.  Assigning  to Lenny to investigate

**Comment by lenny-lunarg** [comment] 2017-03-29 19:34
I checked and the file in question is missing in 1.0.39.1, but it's present in both 1.0.39.0 and 1.0.42.0. I spent a little time looking through the commit history for our build scripts, and I think I see what happened.

It looks like what happened is that between the 1.0.39.0 and 1.0.39.1 releases, the locations of several files (including `vk_dispatch_table_helper.h`) changed on master, and I updated our SDK build scripts. But I screwed up the update so that these files were left out. It looks like we caught this error when testing the pre-release version of 1.0.42.0 (I'm guessing this is what @Tony-LunarG is remembering) and fixed it for 1.0.42.0. But we appear to have missed the problem in the 1.0.39.1 SDK.

As a result, it looks like we already fixed this problem, but the newer SDKs where the problem is fixed (1.0.42.0 and 1.0.42.1) aren't available right now. As a result, you're going to have to wait until another SDK comes out. This should be no later than next week, but I think we'll probably have another SDK ready before the end of this week.

I'm closing this issue, since our build scripts are already fixed. If you find that the problem still exists in any SDK newer than 1.0.39.1, then reopen the issue, but this should be resolved for the next SDK.

**Closed by lenny-lunarg** 2017-03-29 19:34 UTC
